export const emojiResponses: Record<string, string> = {
    "😂": "🤣",    "🤔": "🤨",    "😜": "😝",       
    "👍": "👌",     "😴": "💤",     "🙄": "😒",       
    "🥺": "💖",     "😭": "😢😢",     "😅": "😆",       
    "🔥": "💥",     "😆": "😄",     "🧐": "🤓",       
    "😎": "🕶️",     "🥳": "🎉",     "🤗": "🤭",       
    "😢": "💔",     "💀": "☠️",      "😇": "👼",      
    "🤣": "😂😂",   "💪": "🦸‍♂️",     "🤪": "😝",       
    "😊": "😁",     "😱": "😨",     "🤭": "😶",       
    "🎉": "🥳",     "🤯": "💥",     "😌": "😎",       
    "😡": "😠",     "🤩": "😍",     "🤫": "🤐",       
    "🥴": "😵",     "😈": "👹",     "💅": "💄",      
    "🍕": "🍔",     "🍔": "🍟",     "🌮": "🌯",       
    "🍩": "🍪",     "🍦": "🍧",     "🌻": "🌸",       
    "🌺": "💐",     "🌹": "🌷",     "🌞": "🌚",       
    "🌈": "🌦️",     "☔": "🌧️",     "🌪️": "🌬️",     
    "🌊": "🏖️",     "🎶": "🎧",     "💜": "🖤",       
    "🎤": "🎸",     "🎮": "🕹️",     "💻": "🖥️",     
    "📱": "📲",     "📚": "📝",     "🖋️": "✒️",     
    "🧑‍🍳": "🍴",     "🛀": "🧴",     "💘": "💝",     
    "💉": "💊",     "🤕": "🩹",     "🚀": "🛸",       
    "🚗": "🚙",     "💚": "💙",     "✈️": "🛫",     
    "🚤": "⛵",     "🏡": "🏠",     "🛏️": "🛋️",     
    "💔": "❤️‍🩹",     "🌍": "🌎",     "💼": "🧳",     
    "💃": "🕺",     "🤷‍♂️": "🤷‍♀️",     "🤍": "🤎",   
    "👀": "👁️",     "👑": "💍",     "❤️": "💛",     
    "❤️‍🔥": "🔥",     "💣": "⚡",     "🚧": "⛔",   
  };
  

  export const responses: Record<string, string> = {
    hello: "Hey there!  How can I assist you today?",
    hi: "Hello! What's on your mind?",
    hey: "Hey! How's it going?",
    how: "I'm doing great! How about you?",
    bye: "Goodbye! Have a fantastic day! ",
    goodbye: "See you later! Take care! ",
    thanks: "You're welcome!  Let me know if you need anything else.",
    thank: "No problem at all! Happy to help! ",
    help: "Of course! What do you need help with?",
    weather:
      "I'm not sure about the weather right now. You might want to check a weather app!",
    time: "I don't have a clock, but you can check the time on your device! ",
    sad: "I'm really sorry to hear that. I hope things get better soon! ",
    happy: "That's awesome to hear! Keep spreading the positivity! ",
    music: "Music is the best! What's your favorite genre or artist? ",
    movie:
      "I can't watch movies, but I hear there are some amazing ones out there! What's your favorite? ",
    game: "Games are so much fun! What are you playing these days? ",
    work: "You're doing amazing! Keep up the great work! ",
    sleep: "Good night! Sleep tight and dream big!",
    woke: "Good morning!",
    wake: "Good morning!",
    morning: "Good morning! Hope you have a wonderful day ahead!",
    night: "Good night! Sweet dreams and see you tomorrow!",
    default: "Hmm, I'm not sure how to respond to that. Can you tell me more?",
  };
  